# Generated by Django 5.0.1 on 2024-02-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_highest_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
